### ISSUE TITLE
modify default parameter value of 'serverType' in 'GetPlayerListAsync'

### ISSUE THREAD

**Issue by guerro323** [EvoTM/GbxRemote.Net#17]
## Problem
Calling `GbxRemoteClient.GetPlayerListAsync()` without modifying the last parameters (serverType), which is for now -1, will throw a server error.

`GbxRemoteNet.GbxRemoteClient|Remote call failed with reason: GbxRemoteNet.XmlRpc.Types.XmlRpcFault`

## Solution
Manually modifying serverType to 0 fix the error
`GbxRemoteClient.GetPlayerListAsync(serverType: 0);`

**Comment by guerro323** [comment]
supersed by https://github.com/EvoTM/GbxRemote.Net/issues/18

**Comment by snixtho** [comment]
I cannot reproduce your error on the latest TM2020 dedicated server version (2022-06-21_18_24). The parameter is optional and only for compatibility reasons and shouldn't be used in the newer games. For example setting it to 0 equals compatibility the United game version (which throws an exception for me), which is wrong considering this library is only developed and tested for TM2020 and TM2.

From what I've tested, setting it to -1 or null is the same as just omitting it. But maybe we can just simply completely remove this parameter as it will never be used anyways.
