### ISSUE TITLE
Incorrect call to BanAndBlackListAsync

### ISSUE THREAD

**Issue by snixtho** [EvoTM/GbxRemote.Net#25]
The signature for BanAndBlackList is `BanAndBlackList(string, string, boolean)` and the last parameter is set to null by default. It should be a boolean. If you attempt to call this function, an XMLRPC fault is raised.

https://github.com/EvoTM/GbxRemote.Net/blob/master/GbxRemote.Net/GbxRemoteClient.Methods.Players.cs#L57

**Comment by Chris92de** [comment]
Fixed in dev
