### ISSUE TITLE
Implement missing callbacks...

### ISSUE THREAD

**Issue by reaby** [EvoTM/GbxRemote.Net#26]
for example: PlayerManialinkPageAnswer

see reference here: https://wiki.trackmania.io/en/dedicated-server/XML-RPC/Callbacks

----

Missing callbacks: 
- [x] `ManiaPlanet.BillUpdated`
- [x] `ManiaPlanet.MapListModified`
- [x] `ManiaPlanet.PlayerAlliesChanged`
- [x] `ManiaPlanet.ServerStart`
- [x] `ManiaPlanet.ServerStop`
- [x] `ManiaPlanet.TunnelDataReceived`
- [x] `ManiaPlanet.VoteUpdated`
- [x] `ScriptCloud.LoadData`
- [x] `ScriptCloud.SaveData`

**Comment by snixtho** [comment]
PlayerManialinkPageAnswer was added in #31

**Comment by snixtho** [comment]
Missing callbacks: 
- [ ] `ManiaPlanet.BillUpdated`
- [ ] `ManiaPlanet.MapListModified`
- [ ] `ManiaPlanet.PlayerAlliesChanged`
- [ ] `ManiaPlanet.ServerStart`
- [ ] `ManiaPlanet.ServerStop`
- [ ] `ManiaPlanet.TunnelDataReceived`
- [ ] `ManiaPlanet.VoteUpdated`
- [ ] `ScriptCloud.LoadData`
- [ ] `ScriptCloud.SaveData`
- [ ] `TrackMania.PlayerCheckpoint`
- [ ] `TrackMania.PlayerFinish`
- [ ] `TrackMania.PlayerIncoherence`

*Some callbacks are not used anymore*
