### ISSUE TITLE
Remove Nlog

### ISSUE THREAD

**Issue by snixtho** [EvoTM/GbxRemote.Net#37]
Nlog is an uneccessary bloat to this library causes issues for all projects using it. You are for example forced to include nlog in your project even if you're not using it with this library.

It should be replaced by either a bult-in custom logging system or the Microsoft.Extensions.Logging library as it is much more supported and isnt a huge library like nlog.

**Comment by Chris92de** [comment]
Feel free to remove it.

**Comment by snixtho** [comment]
> Feel free to remove it.

The question is which of the other possibilities to replace it with. Might have to experiment a bit unless you have some clear suggestions.
