### ISSUE TITLE
GetLastConnectionErrorMessageAsync throws NullReferenceException

### ISSUE THREAD

**Issue by AtomicLiquid** [EvoTM/GbxRemote.Net#56]
Currently, if the server didn't manage to connect, GbxRemote returns a NullRefenceException when trying to access GetLastConnectionErrorMessageAsync. To prevent the end-user from having to use a null-check, this null-check should be provided within the method and return an perhaps return a string to the end-user instead.

**Comment by snixtho** [comment]
Well if the client didnt connect, it doesn't make sense to even call the XMLRPC methods. But I think what we can do is to throw an invalid operation exception that will be alot more descriptive of what happened.
